splash = false

preload = ~/.config/hypr/assets/bd1.jpg
preload = ~/.config/hypr/assets/bd2.jpg
preload = ~/.config/hypr/assets/vp1.jpg
preload = ~/.config/hypr/assets/shf1.jpg

wallpaper {
    monitor =
    path = ~/.config/hypr/assets/vp1.jpg
    fit_mode = cover
}

